/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KelasRouteImport } from './routes/kelas'
import { Route as KelasIndexRouteImport } from './routes/kelas/index'
import { Route as KelasAbsensiRouteImport } from './routes/kelas/absensi'
import { Route as KelasEvaluasiRouteImport } from './routes/kelas/evaluasi'
import { Route as KelasKabarRouteImport } from './routes/kelas/kabar'
import { Route as KelasMateriRouteImport } from './routes/kelas/materi'
import { Route as KelasMuridRouteImport } from './routes/kelas/murid'
import { Route as KelasPaketRouteImport } from './routes/kelas/paket'
import { Route as KelasPanduanRouteImport } from './routes/kelas/panduan'
import { Route as KelasProfilRouteImport } from './routes/kelas/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KelasRoute = KelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => rootRouteImport,
} as any)
const KelasIndexRoute = KelasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KelasRoute,
} as any)
const KelasAbsensiRoute = KelasAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => KelasRoute,
} as any)
const KelasEvaluasiRoute = KelasEvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => KelasRoute,
} as any)
const KelasKabarRoute = KelasKabarRouteImport.update({
  id: '/kabar',
  path: '/kabar',
  getParentRoute: () => KelasRoute,
} as any)
const KelasMateriRoute = KelasMateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => KelasRoute,
} as any)
const KelasMuridRoute = KelasMuridRouteImport.update({
  id: '/murid',
  path: '/murid',
  getParentRoute: () => KelasRoute,
} as any)
const KelasPaketRoute = KelasPaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => KelasRoute,
} as any)
const KelasPanduanRoute = KelasPanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => KelasRoute,
} as any)
const KelasProfilRoute = KelasProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => KelasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kelas': typeof KelasRouteWithChildren
  '/kelas/absensi': typeof KelasAbsensiRoute
  '/kelas/evaluasi': typeof KelasEvaluasiRoute
  '/kelas/kabar': typeof KelasKabarRoute
  '/kelas/materi': typeof KelasMateriRoute
  '/kelas/murid': typeof KelasMuridRoute
  '/kelas/paket': typeof KelasPaketRoute
  '/kelas/panduan': typeof KelasPanduanRoute
  '/kelas/profil': typeof KelasProfilRoute
  '/kelas/': typeof KelasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kelas/absensi': typeof KelasAbsensiRoute
  '/kelas/evaluasi': typeof KelasEvaluasiRoute
  '/kelas/kabar': typeof KelasKabarRoute
  '/kelas/materi': typeof KelasMateriRoute
  '/kelas/murid': typeof KelasMuridRoute
  '/kelas/paket': typeof KelasPaketRoute
  '/kelas/panduan': typeof KelasPanduanRoute
  '/kelas/profil': typeof KelasProfilRoute
  '/kelas': typeof KelasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kelas': typeof KelasRouteWithChildren
  '/kelas/absensi': typeof KelasAbsensiRoute
  '/kelas/evaluasi': typeof KelasEvaluasiRoute
  '/kelas/kabar': typeof KelasKabarRoute
  '/kelas/materi': typeof KelasMateriRoute
  '/kelas/murid': typeof KelasMuridRoute
  '/kelas/paket': typeof KelasPaketRoute
  '/kelas/panduan': typeof KelasPanduanRoute
  '/kelas/profil': typeof KelasProfilRoute
  '/kelas/': typeof KelasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kelas'
    | '/kelas/absensi'
    | '/kelas/evaluasi'
    | '/kelas/kabar'
    | '/kelas/materi'
    | '/kelas/murid'
    | '/kelas/paket'
    | '/kelas/panduan'
    | '/kelas/profil'
    | '/kelas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kelas/absensi'
    | '/kelas/evaluasi'
    | '/kelas/kabar'
    | '/kelas/materi'
    | '/kelas/murid'
    | '/kelas/paket'
    | '/kelas/panduan'
    | '/kelas/profil'
    | '/kelas'
  id:
    | '__root__'
    | '/'
    | '/kelas'
    | '/kelas/absensi'
    | '/kelas/evaluasi'
    | '/kelas/kabar'
    | '/kelas/materi'
    | '/kelas/murid'
    | '/kelas/paket'
    | '/kelas/panduan'
    | '/kelas/profil'
    | '/kelas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KelasRoute: typeof KelasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelas': {
      id: '/kelas'
      path: '/kelas'
      fullPath: '/kelas'
      preLoaderRoute: typeof KelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelas/': {
      id: '/kelas/'
      path: '/'
      fullPath: '/kelas/'
      preLoaderRoute: typeof KelasIndexRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/absensi': {
      id: '/kelas/absensi'
      path: '/absensi'
      fullPath: '/kelas/absensi'
      preLoaderRoute: typeof KelasAbsensiRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/evaluasi': {
      id: '/kelas/evaluasi'
      path: '/evaluasi'
      fullPath: '/kelas/evaluasi'
      preLoaderRoute: typeof KelasEvaluasiRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/kabar': {
      id: '/kelas/kabar'
      path: '/kabar'
      fullPath: '/kelas/kabar'
      preLoaderRoute: typeof KelasKabarRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/materi': {
      id: '/kelas/materi'
      path: '/materi'
      fullPath: '/kelas/materi'
      preLoaderRoute: typeof KelasMateriRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/murid': {
      id: '/kelas/murid'
      path: '/murid'
      fullPath: '/kelas/murid'
      preLoaderRoute: typeof KelasMuridRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/paket': {
      id: '/kelas/paket'
      path: '/paket'
      fullPath: '/kelas/paket'
      preLoaderRoute: typeof KelasPaketRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/panduan': {
      id: '/kelas/panduan'
      path: '/panduan'
      fullPath: '/kelas/panduan'
      preLoaderRoute: typeof KelasPanduanRouteImport
      parentRoute: typeof KelasRoute
    }
    '/kelas/profil': {
      id: '/kelas/profil'
      path: '/profil'
      fullPath: '/kelas/profil'
      preLoaderRoute: typeof KelasProfilRouteImport
      parentRoute: typeof KelasRoute
    }
  }
}

interface KelasRouteChildren {
  KelasAbsensiRoute: typeof KelasAbsensiRoute
  KelasEvaluasiRoute: typeof KelasEvaluasiRoute
  KelasKabarRoute: typeof KelasKabarRoute
  KelasMateriRoute: typeof KelasMateriRoute
  KelasMuridRoute: typeof KelasMuridRoute
  KelasPaketRoute: typeof KelasPaketRoute
  KelasPanduanRoute: typeof KelasPanduanRoute
  KelasProfilRoute: typeof KelasProfilRoute
  KelasIndexRoute: typeof KelasIndexRoute
}

const KelasRouteChildren: KelasRouteChildren = {
  KelasAbsensiRoute: KelasAbsensiRoute,
  KelasEvaluasiRoute: KelasEvaluasiRoute,
  KelasKabarRoute: KelasKabarRoute,
  KelasMateriRoute: KelasMateriRoute,
  KelasMuridRoute: KelasMuridRoute,
  KelasPaketRoute: KelasPaketRoute,
  KelasPanduanRoute: KelasPanduanRoute,
  KelasProfilRoute: KelasProfilRoute,
  KelasIndexRoute: KelasIndexRoute,
}

const KelasRouteWithChildren = KelasRoute._addFileChildren(KelasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KelasRoute: KelasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
